import type { Metadata } from "next";
import { Box, MantineProvider, Space } from "@mantine/core";
import { Notifications } from "@mantine/notifications";
import Header, { HeaderProvider } from "./Header";
import { AuthProvider } from "./AuthProvider";
import { ModalsProvider } from "@mantine/modals";
import { Navigation } from "./Navigation";
import "@mantine/core/styles.css";
import { BrowseSharesProvider } from "./browse_shares/BrowseSharesContext";
import { UserMenu } from "./UserMenu";

export const metadata: Metadata = {
  title: "Slskd",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head></head>
      <body>
        <MantineProvider>
          <Notifications />
          <ModalsProvider>
            <AuthProvider>
              <BrowseSharesProvider>
                <HeaderProvider>
                  <Box
                    style={{
                      position: "fixed",
                      top: 0,
                      left: 0,
                      right: 0,
                      backgroundColor: "var(--mantine-color-body)",
                      zIndex: 100,
                    }}
                  >
                    <Header />
                    <Navigation />
                  </Box>
                  <Box
                    style={{
                      position: "fixed",
                      top: 10,
                      right: 10,
                      zIndex: 101,
                    }}
                  >
                    <UserMenu />
                  </Box>
                  <Space h={65} />
                  <Box p="lg">{children}</Box>
                </HeaderProvider>
              </BrowseSharesProvider>
            </AuthProvider>
          </ModalsProvider>
        </MantineProvider>
      </body>
    </html>
  );
}
