import type { Metadata } from "next";
import { MantineProvider } from "@mantine/core";
import { Notifications } from "@mantine/notifications";
import { HeaderProvider } from "./Header";
import { AuthProvider } from "./AuthProvider";
import { ModalsProvider } from "@mantine/modals";
import "@mantine/core/styles.css";

export const metadata: Metadata = {
  title: "Slskd",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head></head>
      <body>
        <MantineProvider>
          <Notifications />
          <ModalsProvider>
            <AuthProvider>
              <HeaderProvider>{children}</HeaderProvider>
            </AuthProvider>
          </ModalsProvider>
        </MantineProvider>
      </body>
    </html>
  );
}
