import type { Metadata } from "next";
import { MantineProvider } from "@mantine/core";
import { Notifications } from "@mantine/notifications";
import { AuthProvider } from "./AuthProvider";
import { ModalsProvider } from "@mantine/modals";
import { BrowseSharesProvider } from "./browse_shares/BrowseSharesContext";
import { DownloadsProvider } from "./downloads/DownloadsContext";
import { Suspense } from "react";
import App from "./App";
import "@mantine/core/styles.css";
import "@mantine/notifications/styles.css";
import "./globals.css";
import { CurrentSearchProvider } from "./search_files/CurrentSearchContext";
import { SearchesHistoryProvider } from "./search_files/SearchesHistoryContext";
import { DownloadProvider } from "@/components/DownloadContext";

export const metadata: Metadata = {
  title: "Slskd",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <head></head>
      <body>
        <MantineProvider>
          <Notifications position="top-right" />
          <ModalsProvider>
            <AuthProvider>
              <Suspense fallback={<div>Loading...</div>}>
                <DownloadProvider>
                  <SearchesHistoryProvider>
                    <CurrentSearchProvider>
                      <BrowseSharesProvider>
                        <DownloadsProvider>
                          <App>{children}</App>
                        </DownloadsProvider>
                      </BrowseSharesProvider>
                    </CurrentSearchProvider>
                  </SearchesHistoryProvider>
                </DownloadProvider>
              </Suspense>
            </AuthProvider>
          </ModalsProvider>
        </MantineProvider>
      </body>
    </html>
  );
}
